class RecipeData {
  static final Map<String, List<String>> _recipes = {
    'tomato': [
      'Tomato Pasta with Basil',
      'Fresh Tomato Salsa',
      'Caprese Salad',
      'Tomato Soup',
      'Bruschetta with Tomatoes',
      'Ratatouille',
      'Tomato Curry',
      'Gazpacho',
    ],
    'onion': [
      'French Onion Soup',
      'Caramelized Onion Tart',
      'Onion Rings',
      'Stuffed Onions',
      'Onion Bhaji',
      'Pickled Red Onions',
      'Onion Gravy',
    ],
    'garlic': [
      'Garlic Bread',
      'Garlic Butter Shrimp',
      'Roasted Garlic Soup',
      'Garlic Aioli',
      'Garlic Fried Rice',
      'Garlic Roasted Vegetables',
      'Garlic Herb Chicken',
    ],
    'potato': [
      'Mashed Potatoes',
      'French Fries',
      'Potato Salad',
      'Baked Potato',
      'Hash Browns',
      'Potato Curry',
      'Potato Gratin',
      'Shepherd\'s Pie',
    ],
    'carrot': [
      'Carrot Cake',
      'Glazed Carrots',
      'Carrot Soup',
      'Carrot Salad',
      'Roasted Carrots',
      'Carrot Ginger Soup',
      'Carrot Stir Fry',
    ],
    'bell pepper': [
      'Stuffed Bell Peppers',
      'Bell Pepper Stir Fry',
      'Roasted Red Pepper Soup',
      'Pepper Salad',
      'Bell Pepper Fajitas',
      'Ratatouille',
      'Pepper and Onion Pasta',
    ],
    'mushroom': [
      'Mushroom Risotto',
      'Stuffed Mushrooms',
      'Mushroom Soup',
      'Mushroom Stir Fry',
      'Mushroom Pasta',
      'Grilled Portobello',
      'Mushroom Omelet',
    ],
    'broccoli': [
      'Broccoli Cheese Soup',
      'Steamed Broccoli',
      'Broccoli Stir Fry',
      'Broccoli Salad',
      'Broccoli Casserole',
      'Roasted Broccoli',
      'Broccoli Pasta',
    ],
    'spinach': [
      'Spinach Salad',
      'Creamed Spinach',
      'Spinach Quiche',
      'Spinach Pasta',
      'Spinach Smoothie',
      'Saag Paneer',
      'Spinach Omelet',
    ],
    'corn': [
      'Corn on the Cob',
      'Corn Salad',
      'Corn Soup',
      'Corn Bread',
      'Mexican Street Corn',
      'Corn Chowder',
      'Corn Fritters',
    ],
    'apple': [
      'Apple Pie',
      'Apple Crisp',
      'Apple Sauce',
      'Apple Salad',
      'Caramel Apples',
      'Apple Juice',
      'Apple Butter',
      'Apple Strudel',
    ],
    'banana': [
      'Banana Bread',
      'Banana Smoothie',
      'Banana Pancakes',
      'Banana Split',
      'Banana Muffins',
      'Fried Bananas',
      'Banana Pudding',
    ],
    'orange': [
      'Orange Juice',
      'Orange Cake',
      'Orange Chicken',
      'Orange Salad',
      'Orange Smoothie',
      'Orange Marmalade',
      'Orange Sorbet',
    ],
    'lemon': [
      'Lemon Pie',
      'Lemon Chicken',
      'Lemon Water',
      'Lemon Bars',
      'Lemon Cake',
      'Lemon Sorbet',
      'Lemon Vinaigrette',
    ],
    'strawberry': [
      'Strawberry Shortcake',
      'Strawberry Smoothie',
      'Strawberry Jam',
      'Strawberry Salad',
      'Chocolate Strawberries',
      'Strawberry Pie',
      'Strawberry Milkshake',
    ],
    'chicken': [
      'Grilled Chicken',
      'Chicken Curry',
      'Chicken Soup',
      'Fried Chicken',
      'Chicken Salad',
      'Chicken Stir Fry',
      'Chicken Parmesan',
      'Buffalo Chicken',
    ],
    'beef': [
      'Beef Stew',
      'Grilled Steak',
      'Beef Curry',
      'Beef Tacos',
      'Beef Stroganoff',
      'Beef Burgers',
      'Beef Stir Fry',
    ],
    'fish': [
      'Grilled Fish',
      'Fish Curry',
      'Fish Soup',
      'Fish Tacos',
      'Baked Fish',
      'Fish and Chips',
      'Fish Salad',
    ],
    'rice': [
      'Fried Rice',
      'Rice Pilaf',
      'Rice Pudding',
      'Spanish Rice',
      'Rice Salad',
      'Coconut Rice',
      'Rice Stir Fry',
    ],
    'pasta': [
      'Spaghetti Carbonara',
      'Pasta Salad',
      'Pasta Primavera',
      'Lasagna',
      'Pasta with Marinara',
      'Pasta Alfredo',
      'Pasta Bolognese',
    ],
    'egg': [
      'Scrambled Eggs',
      'Fried Eggs',
      'Egg Salad',
      'Deviled Eggs',
      'Egg Curry',
      'Egg Sandwich',
      'Egg Fried Rice',
      'Omelet',
    ],
    'cheese': [
      'Cheese Sandwich',
      'Mac and Cheese',
      'Cheese Soup',
      'Cheese Cake',
      'Cheese Salad',
      'Cheese Fondue',
      'Cheese Quesadilla',
    ],
    'bread': [
      'Garlic Bread',
      'French Toast',
      'Bread Pudding',
      'Sandwiches',
      'Bread Salad',
      'Stuffing',
      'Bread Crumbs',
    ],
  };

  static List<String> getRecipes(String ingredient) {
    final key = ingredient.toLowerCase();
    return _recipes[key] ?? [
      'No specific recipes found for $ingredient',
      'Try searching online for "$ingredient recipes"',
      'Consider using $ingredient in salads or stir-fries',
    ];
  }

  static List<String> getAllIngredients() {
    return _recipes.keys.toList();
  }
}